import React from "react"

const layouts = [
  {
    id: 0,
    description:
      "1 manchete sem foto | 2 destaques sem foto | 1 manchete com foto |  5 matérias sem foto",
    svg: (
      <svg width="112" height="53" xmlns="http://www.w3.org/2000/svg">
        <g>
          <rect
            stroke="#000"
            id="svg_1"
            height="53"
            width="53"
            fill="#BBBBBB"
          />
          <rect
            id="svg_3"
            height="22"
            width="22"
            y="0"
            x="60"
            stroke="#000"
            fill="#BBBBBB"
          />
          <rect
            id="svg_4"
            height="22"
            width="22"
            y="0"
            x="89"
            stroke="#000"
            fill="#BBBBBB"
          />
          <path
            stroke="#000"
            id="svg_5"
            d="m90,41l21.43909,0"
            opacity="undefined"
            fill="none"
          />
          <path
            stroke="#000"
            id="svg_6"
            d="m90,32l21.43909,0"
            opacity="undefined"
            fill="none"
          />
          <path
            stroke="#000"
            id="svg_7"
            d="m90,50l21.43909,0"
            opacity="undefined"
            fill="none"
          />
          <path
            stroke="#000"
            id="svg_8"
            d="m61,41l21.43909,0"
            opacity="undefined"
            fill="none"
          />
          <path
            stroke="#000"
            id="svg_9"
            d="m61,32l21.43909,0"
            opacity="undefined"
            fill="none"
          />
          <path
            stroke="#000"
            id="svg_10"
            d="m61,50l21.43909,0"
            opacity="undefined"
            fill="none"
          />
        </g>
      </svg>
    ),
  },
  {
    id: 1,
    description: "1 manchete com foto, 4 destaques com foto",
    svg: (
      <svg width="112" height="53" xmlns="http://www.w3.org/2000/svg">
        <g>
          <title>Layer 1</title>
          <rect
            fill="#BBBBBB"
            width="53"
            height="53"
            id="svg_1"
            stroke="#000"
          />
          <rect
            fill="#BBBBBB"
            stroke="#000"
            x="60"
            y="0"
            width="22"
            height="22"
            id="svg_3"
          />
          <rect
            fill="#BBBBBB"
            stroke="#000"
            x="89"
            y="0"
            width="22"
            height="22"
            id="svg_4"
          />
          <rect
            fill="#BBBBBB"
            stroke="#000"
            x="61"
            y="31"
            width="22"
            height="22"
            id="svg_2"
          />
          <rect
            fill="#BBBBBB"
            stroke="#000"
            x="90"
            y="31"
            width="22"
            height="22"
            id="svg_5"
          />
        </g>
      </svg>
    ),
  },
  {
    id: 2,
    description: "1 manchete sem foto, 4 destaques com foto",
    svg: (
      <svg width="112" height="53" xmlns="http://www.w3.org/2000/svg">
        <g>
          <title>Layer 1</title>
          <rect
            y="30"
            stroke="#000"
            id="svg_1"
            height="23"
            width="23"
            fill="#BBBBBB"
            x="89"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_4"
            y2="4"
            x2="50.54278"
            y1="4"
            x1="4"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_6"
            y2="16"
            x2="50.54278"
            y1="16"
            x1="4"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_7"
            y2="27"
            x2="51.54278"
            y1="27"
            x1="5"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_8"
            y2="39"
            x2="51.54278"
            y1="39"
            x1="5"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_9"
            y2="51"
            x2="51.54278"
            y1="51"
            x1="5"
            fill="none"
          />
          <rect
            y="30"
            stroke="#000"
            id="svg_2"
            height="23"
            width="23"
            fill="#BBBBBB"
            x="60"
          />
          <rect
            y="2"
            stroke="#000"
            id="svg_3"
            height="23"
            width="23"
            fill="#BBBBBB"
            x="89"
          />
          <rect
            y="2"
            stroke="#000"
            id="svg_5"
            height="23"
            width="23"
            fill="#BBBBBB"
            x="60"
          />
        </g>
      </svg>
    ),
  },
  {
    id: 3,
    description: "1 manchete sem foto, 1 manchete com foto",
    svg: (
      <svg width="112" height="53" xmlns="http://www.w3.org/2000/svg">
        <g>
          <title>Layer 1</title>
          <rect
            stroke="#000"
            id="svg_1"
            height="53"
            width="53"
            fill="#BBBBBB"
            y="0"
            x="59"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_4"
            y2="4"
            x2="50.54278"
            y1="4"
            x1="4"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_6"
            y2="16"
            x2="50.54278"
            y1="16"
            x1="4"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_7"
            y2="27"
            x2="51.54278"
            y1="27"
            x1="5"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_8"
            y2="39"
            x2="51.54278"
            y1="39"
            x1="5"
            fill="none"
          />
          <line
            stroke="#000"
            strokeWidth="4"
            id="svg_9"
            y2="51"
            x2="51.54278"
            y1="51"
            x1="5"
            fill="none"
          />
        </g>
      </svg>
    ),
  },
]

export default layouts
